apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: xprtz-argo-cd
  name: xprtz-argo-cd-app
spec:
  project: xprtz-argo-cd-project
  source:
    # This is the repository ArgoCD will use to sync the application
    repoURL: https://github.com/RednasN/argocd-test.git
    targetRevision: main
    path: app
    directory:
      recurse: true
  destination:
    # This is the cluster ArgoCD will deploy the application to
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: false
      selfHeal: true